
[34m[1mwandb[39m[22m: logging graph, to disable use `wandb.watch(log_graph=False)`
Traceback (most recent call last):
  File "session-5/main.py", line 75, in <module>
    run_reconstruction(
  File "C:\Users\joanpg5\Documents\aidl-2023-winter-mlops\session-5\run_reconstruction.py", line 94, in run_reconstruction
    logger.log_reconstruction_training(
  File "C:\Users\joanpg5\Documents\aidl-2023-winter-mlops\session-5\wandb_TODO.py", line 45, in log_reconstruction_training
    wandb.log(("train reconstruction loss", train_loss_avg), epoch)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\wandb_run.py", line 1548, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\joanpg5\.conda\envs\aidl-session5\lib\site-packages\wandb\sdk\wandb_run.py", line 1334, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary